### ISSUE TITLE
error in app, cant open it

### ISSUE THREAD

**Issue by nexus4alii1991** [alexakasanjeev/magento_react_native#34]
hi,
I am using magento 2.2.8, and react native 0.58.6 on windows 8, installed sdk 28. i run the command react-native run android and the app is installed on the device but it shows this error: "Property description must be an object"
check the image to see the error in the app:
![Screenshot_20190710-222805](https://user-images.githubusercontent.com/46761793/60998808-5504a100-a362-11e9-914b-1394529e58f3.png)

**Comment by alexakasanjeev** [comment]
Hi @nexus4alii1991 Can you love me more context, In which file this error is coming, because in Screenshot no file is mentioned.

Steps todo:
1. Scroll the error screen and send me those screenshots as well.
2. Enable Remore JS debug mode, by pressing `ctrl + m` and selecting Start remote JS Debugging. [ref](https://facebook.github.io/react-native/docs/debugging)
3. This will launch a new tab on chrome, reload the app by pressing `R,R`
4. Open the developer console in chrome by pressing `ctrl + shift + j`
5. If there is Error log in there send that too.

**Comment by nexus4alii1991** [comment]
![Screenshot_20190711-004259](https://user-images.githubusercontent.com/46761793/61007362-512e4a00-a375-11e9-99bd-78ff64450326.png)
![Screenshot_20190711-004316](https://user-images.githubusercontent.com/46761793/61007363-51c6e080-a375-11e9-879a-dcc6821e9e3d.png)
![Screenshot_20190711-004334](https://user-images.githubusercontent.com/46761793/61007365-5390a400-a375-11e9-8384-fac7819d03d4.png)
![Screenshot_20190711-004347](https://user-images.githubusercontent.com/46761793/61007378-57bcc180-a375-11e9-8eb2-8c8effcd0806.png)
![Screenshot_20190711-004401](https://user-images.githubusercontent.com/46761793/61007392-61462980-a375-11e9-868e-98dc50f507d9.png)
![Screenshot_20190711-004410](https://user-images.githubusercontent.com/46761793/61007393-61dec000-a375-11e9-9420-d13440baac33.png)
![Screenshot_20190711-004416](https://user-images.githubusercontent.com/46761793/61007394-61dec000-a375-11e9-80be-433f880901e3.png)

Thanks for the reply, this is the complete screenshots of the whole error. regarding other request i am using debugging via usb connection and not wifi via chrome. I will switch to chrome and follow your steps. I am still new to react native, currently i am re-installing it from scratch to make sure it is not a problem from my installation and rerun the code again.
Remark, at first i was using react-native 0.59 and the app gave errors but opened, but it didnt work properly it gave text "function null undefined".
Thanks for the help, good work :)

**Comment by alexakasanjeev** [comment]
Hi @nexus4alii1991, Thanks for the screenshots,  but this doesn't convey any helpful information, can you try using remote debugging, and you can use Remote debugging on device/emulator via usb, you don't need wifi, if you are testing on real device, just shake your device, and the same menu will pop up which pops up when you hit `ctrl + m`.

1. Try looking in console and report the error here.
2. You can share your magento url along with intregation code(you can mail me or send private on slack or here if the store is not production), so that I can check too.

**Comment by alexakasanjeev** [comment]
Hi @nexus4alii1991 any updates, otherwise this issue will be closed soon
